import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { validate } from "@mapbox/mapbox-gl-style-spec";

const route = "/maps/GeoJSON/A_M-light";

async function render(pathname = route) {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}-${Math.random()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request(`http://localhost${pathname}`, {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("serves the California Light map at the requested route", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>California Light · NaviJSON<\/title>/i);
  assert.match(html, /NaviJSON/);
  assert.match(html, /in a clearer light\./);
  assert.match(html, /No-key preview/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/i);
});

test("root URL redirects to the California Light map", async () => {
  const response = await render("/");
  assert.ok([301, 302, 307, 308].includes(response.status));
  assert.equal(new URL(response.headers.get("location"), "http://localhost").pathname, route);
});

test("ships valid GeoJSON and a structurally valid Mapbox style", async () => {
  const [styleText, geoJsonText, tokensText] = await Promise.all([
    readFile(new URL("../public/maps/GeoJSON/A_M-light/style.json", import.meta.url), "utf8"),
    readFile(new URL("../public/maps/GeoJSON/A_M-light/features.geojson", import.meta.url), "utf8"),
    readFile(new URL("../public/maps/GeoJSON/A_M-light/tokens.json", import.meta.url), "utf8"),
  ]);

  const style = JSON.parse(styleText);
  const geoJson = JSON.parse(geoJsonText);
  const tokens = JSON.parse(tokensText);

  assert.equal(style.version, 8);
  assert.equal(style.name, "NaviJSON California Light");
  assert.equal(style.sources["navijson-reality"].type, "geojson");
  assert.equal(geoJson.type, "FeatureCollection");
  assert.ok(geoJson.features.length >= 25);
  assert.equal(tokens.variant, "A_M-light");

  const fatalValidationErrors = validate(style).filter(
    (error) => !/imports|slot|config/.test(error.message),
  );
  assert.deepEqual(fatalValidationErrors, []);
});

async function loadFeatures() {
  const text = await readFile(
    new URL("../public/maps/GeoJSON/A_M-light/features.geojson", import.meta.url),
    "utf8",
  );
  const geoJson = JSON.parse(text);
  assert.equal(geoJson.type, "FeatureCollection");
  return geoJson.features;
}

test("Reality Layer is a large OpenStreetMap-derived feature set, not a hand-drawn fixture", async () => {
  const features = await loadFeatures();

  // The Reality Layer is now generated by scripts/pipeline from OpenStreetMap
  // (thousands of features across the committed California sample regions), not
  // the old ~33-feature hand-drawn fixture.
  assert.ok(
    features.length >= 1000,
    `expected a large OSM-derived feature set, got ${features.length}`,
  );
});

test("Reality Layer carries the full enriched feature-type coverage", async () => {
  const features = await loadFeatures();
  const featureTypes = new Set(features.map((feature) => feature.properties?.feature_type));

  // Representative categories that must stay present so the enrichment can't
  // silently regress toward a sparse fixture.
  const requiredTypes = [
    "road",
    "lane_divider",
    "building",
    "signal",
    "street_lamp",
    "stop_sign",
    "crossing",
    "park",
    "rail",
    "sidewalk",
  ];
  for (const featureType of requiredTypes) {
    assert.ok(featureTypes.has(featureType), `expected feature_type "${featureType}" to be present`);
  }

  // Water is represented as `water` polygons and/or `waterway` lines depending
  // on what the region contains; require at least one form.
  assert.ok(
    featureTypes.has("water") || featureTypes.has("waterway"),
    "expected water or waterway features to be present",
  );
});

test("Reality Layer paints lane markings, including a double-yellow centerline", async () => {
  const features = await loadFeatures();

  const laneDividers = features.filter(
    (feature) => feature.properties?.feature_type === "lane_divider",
  );
  assert.ok(laneDividers.length >= 1, "expected at least one lane_divider (road paint) feature");

  const centerline = laneDividers.find((feature) => feature.properties?.nj_class === "centerline");
  assert.ok(centerline, "expected at least one lane_divider with nj_class === \"centerline\"");
});

test("Reality Layer includes grade-separated features (overpasses/underpasses)", async () => {
  const features = await loadFeatures();

  const bridged = features.find((feature) => feature.properties?.bridge === true);
  assert.ok(bridged, "expected at least one feature with properties.bridge === true");
});

test("every Reality Layer feature carries an OpenStreetMap provenance envelope", async () => {
  const features = await loadFeatures();

  for (const feature of features) {
    const props = feature.properties ?? {};
    assert.equal(props.source, "openstreetmap", `feature ${props.source_ref} missing OSM source`);
    assert.ok(
      typeof props.source_ref === "string" && props.source_ref.length > 0,
      "every feature must record a source_ref",
    );
    assert.equal(props.license, "ODbL", "every feature must be licensed ODbL");
    assert.equal(typeof props.confidence, "number", "confidence must be numeric");
    assert.ok(
      props.confidence >= 0 && props.confidence <= 1,
      `confidence out of range: ${props.confidence}`,
    );
  }
});
